version: '3'

includes:
  local:
    taskfile: ./taskfile.local.yaml
    optional: true

tasks:
  default:
    cmds:
      - task: publish
      - task: local:install
    
  publish: dotnet publish -c Release -o ./out AzureAuth
