name: Build and publish release

on:
  release:
    types: [published]


jobs:
  run:
    continue-on-error: true
    strategy:
        matrix:
          include:
            - target: win-x64
              os: windows-latest
            - target: win-arm64
              os: windows-latest
            - target: linux-x64
              os: ubuntu-latest
            - target: linux-arm64
              os: macos-latest
            - target: linux-musl-x64 
              os: ubuntu-latest
            - target: linux-musl-arm64
              os: macos-latest
            - target: osx-x64
              os: macos-latest
            - target: osx-arm64
              os: macos-latest
    runs-on: ${{matrix.os}}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet publish -c Release -r ${{matrix.target}} -o out AzureAuth
    - name: Move
      shell: bash
      run: |
        mkdir assets
        mv out/azure-auth.exe assets/azure-auth.${{matrix.target}}.exe || true
        mv out/azure-auth assets/azure-auth.${{matrix.target}} || true
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: assets/*
