name: Build and publish release

on:
  release:
    types: [published]


jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
        matrix:
          target: [win-x64, win-x86, win-arm64, linux-x64, linux-musl-x64, linux-musl-arm64, linux-arm, linux-arm64, osx-x64, osx-arm64]
          
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet publish -c Release -o out AzureAuth
    - name: Move
      run: |
        mkdir assets
        mv out/azure-auth.exe assets/azure-auth.${{matrix-target}}.exe
        mv out/azure-auth assets/azure-auth.${{matrix-target}}
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: ${{matrix.target}}/azure-auth*
